version: "3"

services:
  task-management-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: loei-a6-express
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: nodemon --watch . --exec "node" index.js

  db:
    image: mysql
    container_name: task-management-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: task_management
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    cap_add:
      - SYS_NICE

volumes:
  db_data:
    name: "db_data"

networks:
  default:
    external:
      name: default-net
